// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NguyenDuyenCuong114.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("NguyenDuyenCuong114.NDCStudent", b =>
                {
                    b.Property<string>("NDCStudentID")
                        .HasColumnType("TEXT");

                    b.Property<string>("NDCStudentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sdt")
                        .HasColumnType("INTEGER");

                    b.HasKey("NDCStudentID");

                    b.ToTable("NDCStudent");
                });
#pragma warning restore 612, 618
        }
    }
}
